condense_wildcard_suffixes = true
empty_item_single_line = true
error_on_line_overflow = true
error_on_unformatted = true
format_code_in_doc_comments = true
format_strings = true
match_block_trailing_comma = true
merge_imports = true
newline_style = "Unix"
normalize_doc_attributes = true
reorder_impl_items = true
use_field_init_shorthand = true
version = "Two"
wrap_comments = true